# Generated by Django 5.0.6 on 2024-07-26 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0004_category_imges'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdectEnter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generate_code', models.CharField(blank=True, max_length=255, unique=True)),
                ('quantity', models.IntegerField()),
                ('old_quantity', models.IntegerField(blank=True)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Goods.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
